version: "3.7"

services:
  arweave_processor:
    build:
      context: .
      dockerfile: jobs/arweave_processor/dockerfile
    env_file:
      - arweave_processor.local.env

  arweave_util:
    build:
      context: .
      dockerfile: jobs/arweave_processor/util.dockerfile
    env_file:
      - arweave_processor.local.env

  near_processor:
    build:
      context: .
      dockerfile: jobs/near_processor/dockerfile
    env_file:
      - near_processor.local.env
  
  near_util:
    build:
      context: .
      dockerfile: jobs/near_processor/util.dockerfile
    env_file:
      - near_processor.local.env

  vault_processor:
    build:
      context: .
      dockerfile: jobs/vault_processor/dockerfile
    env_file:
      - vault_processor.local.env
  
  vault_util:
    build:
      context: .
      dockerfile: jobs/vault_processor/util.dockerfile
    env_file: vault_processor.local.env

  vault:
    build:
      context: frontend/vault
      dockerfile: testnet.dockerfile
    ports:
      - 8000:3000
  

  