version: "3.7"

services:
  arweave_processor:
    build:
      context: jobs/arweave_processor
      dockerfile: local.dockerfile
    entrypoint: [npm, run]
    command: dev:watch
    working_dir: /home/app/jobs/arweave_processor
    volumes:
      - ./jobs/arweave_processor:/home/app/jobs/arweave_processor
      - ./lib:/home/app/lib

  arweave_callback:
    build:
      context: jobs/arweave_processor
      dockerfile: local.dockerfile
    entrypoint: [npm, run]
    command: callback-server
    working_dir: /home/app/jobs/arweave_processor
    volumes:
      - ./jobs/arweave_processor:/home/app/jobs/arweave_processor
      - ./lib:/home/app/lib

  near_processor:
    build:
      context: jobs/near_processor
      dockerfile: local.dockerfile
    entrypoint: yarn
    command: dev:watch
    working_dir: /home/app
    volumes:
      - ./jobs/near_processor:/home/app

  near_callback:
    build:
      context: jobs/near_processor
      dockerfile: local.dockerfile
    entrypoint: yarn
    command: callback-server
    working_dir: /home/app
    volumes:
      - ./jobs/near_processor:/home/app
  
  vault_processor:
    build:
      context: jobs/vault_processor
      dockerfile: local.dockerfile
    entrypoint: yarn
    command: dev:watch
    working_dir: /home/app
    volumes:
      - ./jobs/vault_processor:/home/app
  
  vault_front:
    build:
      context: frontend/vault
      dockerfile: local.dockerfile
    entrypoint: npm
    command: ["run", "start"]
    working_dir: /home/app
    ports:
      - 3000:3000
    volumes:
      - ./frontend/vault:/home/app