version: "3.7"

services:
  arweave_processor:
    build:
      context: .
      dockerfile: jobs/arweave_processor/dockerfile
    env_file:
      - arweave_processor.env
    restart: unless-stopped

  near_processor:
    build:
      context: .
      dockerfile: jobs/near_processor/dockerfile
    env_file:
      - near_processor.env
    restart: unless-stopped
  
  vault_processor:
    build:
      context: .
      dockerfile: jobs/vault_processor/dockerfile
    env_file:
      - vault_processor.env
    restart: unless-stopped
