FROM node:16.6.2 as build

# Build from root directory of the project
WORKDIR /workdir
COPY ./lib /workdir/lib
COPY ./jobs/arweave_processor /workdir/jobs/arweave_processor

# Install dependencies
RUN apt-get update && \
    apt-get -y install git

# Build library
RUN cd lib && \
    npm run build && \
    npm pack

# Build App
RUN cd ./jobs/arweave_processor && \
    npm add ../../lib/lib-1.0.0.tgz && \
    npm install && \
    npm run build && \
    rm -rf node_modules && \
    NODE_ENV=production npm install

FROM node:16.6.2-alpine3.14 as runtime

WORKDIR /home/arweave-processor

COPY --from=build /workdir/jobs/arweave_processor/dist /home/arweave-processor/dist
COPY --from=build /workdir/jobs/arweave_processor/node_modules /home/arweave-processor/node_modules
COPY --from=build /workdir/jobs/arweave_processor/package.json /home/arweave-processor/package.json

ENV NODE_ENV production

LABEL Maintainer="Marc Par <marc.par10@gmail.com>"
LABEL Repository="https://github.com/marcpar/near-nft-processor"
USER node

ENTRYPOINT ["sh", "-c"]
CMD ["node dist/index.js"]
