FROM node:16.6.2 as build

WORKDIR /workdir
COPY ./lib /workdir/lib
COPY ./jobs/vault_processor /workdir/jobs/vault_processor

# Build library
RUN cd lib && \
    npm install && \
    npm run build && \
    npm pack

# Build App
RUN cd ./jobs/vault_processor && \
    yarn add file:/workdir/lib/lib-1.0.0.tgz && \
    yarn install && \
    yarn run build && \
    rm -rf node_modules && \
    NODE_ENV=production yarn install

FROM node:16.6.2-alpine3.14 as runtime

WORKDIR /home/vault-processor

COPY --from=build /workdir/jobs/vault_processor/dist /home/vault-processor/dist
COPY --from=build /workdir/jobs/vault_processor/node_modules /home/vault-processor/node_modules
COPY --from=build /workdir/jobs/vault_processor/package.json /home/vault-processor/package.json
COPY --from=build /workdir/jobs/vault_processor/yarn.lock /home/vault-processor/yarn.lock

ENV NODE_ENV production

RUN chown -R node:node /home/vault-processor && \
    find /home/vault-processor -type f -exec chmod 400 {} \; && \
    find /home/vault-processor -type d -exec chmod 500 {} \;

LABEL Maintainer="Marc Par <marc.par10@gmail.com>"
LABEL Repository="https://github.com/marcpar/near-nft-processor"
USER node

ENTRYPOINT ["sh", "-c"]
CMD ["node dist/index.js"]
