{
 "title": "New dashboard",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "clickhouse_datasource",
    "label": "Clickhouse Datasource",
    "query": "vertamedia-clickhouse-datasource"
   },
   {
    "name": "service_name",
    "query": "SELECT service_name from grafana.t_near_processor_logs"
   },
   {
    "name": "log_type",
    "query": "SELECT log_type from grafana.t_near_processor_logs"
   },
   {
    "name": "level",
    "query": "SELECT level from grafana.t_near_processor_logs"
   }
  ]
 },
 "panels": [
  { "title": "Service Monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Testnet Transaction Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT \n  $__unixEpochGroup(block_timestamp,'5m') as time,\n  receiver_account_id,\n  count(receiver_account_id)\nFROM transactions \nWHERE\n  $__unixEpochNanoFilter(block_timestamp)\tAND\n  receiver_account_id IN ('vault.world-triathlon.testnet', 'nft.world-triathlon.testnet', 'asheltie.testnet')\nGROUP BY\n  time, receiver_account_id"
    }
   ]
  },
  {
   "title": "Log Count Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "database": "grafana",
     "dateTimeColDataType": "time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    concat(service_name, '-', log_type) as label,\n    count()\nFROM $table\n\nWHERE $timeFilter AND\nlog_type in ($log_type) AND\nservice_name in ($service_name) AND\nlevel in ($level)\n\nGROUP BY t, label\n\nORDER BY t, label\n",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(time), 60) * 60) * 1000 as t,\n    concat(service_name, '-', log_type) as label,\n    count()\nFROM grafana.t_near_processor_logs\n\nWHERE time >= toDateTime(1664794301) AND time <= toDateTime(1664796101) AND\nlog_type in ('','default') AND\nservice_name in ('near_processor','arweave_processor') AND\nlevel in ('debug')\n\nGROUP BY t, label\n\nORDER BY t, label",
     "round": "0s",
     "table": "t_near_processor_logs"
    }
   ]
  },
  {
   "title": "Testnet Transaction Logs",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT \n  block_timestamp,\n  signer_account_id,\n  receiver_account_id,\n  status,\n  action_kind,\n  args\nFROM transactions \nLEFT JOIN transaction_actions ON transaction_actions.transaction_hash = transactions.transaction_hash\nWHERE\n  $__unixEpochNanoFilter(block_timestamp)\tAND\n  receiver_account_id IN ('vault.world-triathlon.testnet')\n"
    }
   ]
  },
  {
   "title": "Service Logs",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "database": "grafana",
     "dateTimeColDataType": "time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    time,\n    level,\n    log_type,\n    service_name,\n    message\n    \nFROM $table\n\nWHERE $timeFilter AND\nlog_type in ($log_type) AND\nservice_name in ($service_name) AND\nlevel in ($level)\n\n",
     "rawQuery": "SELECT\n    time,\n    level,\n    log_type,\n    service_name,\n    message\n    \nFROM grafana.t_near_processor_logs\n\nWHERE time >= toDateTime(1664794317) AND time <= toDateTime(1664796117) AND\nlog_type in ('','default') AND\nservice_name in ('near_processor','arweave_processor') AND\nlevel in ('debug')",
     "round": "0s",
     "table": "t_near_processor_logs"
    }
   ]
  },
  { "title": "Container Monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Container Logs",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "database": "grafana",
     "dateTimeColDataType": "time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    time, stream, log, log_path\nFROM $table\n\nWHERE $timeFilter\n",
     "rawQuery": "SELECT\n    time, stream, log, log_path\nFROM grafana.t_docker_logs\n\nWHERE time >= toDateTime(1664793004) AND time <= toDateTime(1664794804)",
     "round": "0s",
     "table": "t_docker_logs"
    }
   ]
  }
 ]
}